apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: da-vespa
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  serviceName: {{ .Values.service.name }}   # This should match service.yaml/metadata/name
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml .Values.podLabels | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vespa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.statefulSet.ports }}
            - containerPort: {{ .containerPort }}
          {{- end }}
#           readinessProbe:
#             httpGet:
#               path: {{ .Values.readinessProbe.httpGet.path }}
#               port: {{ .Values.readinessProbe.httpGet.port }}
#               scheme: {{ .Values.readinessProbe.httpGet.scheme }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          - name: VESPA_CONFIGSERVERS
            value: da-vespa-0.{{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local

  volumeClaimTemplates:
  {{- range .Values.volumeClaimTemplates }}
  - metadata:
      name: {{ .metadata.name }}
    spec:
      accessModes: {{ .spec.accessModes }}
      storageClassName: {{ .spec.storageClassName }}
      resources:
        requests:
          storage: {{ .spec.resources.requests.storage }}
  {{- end }}
